FROM amazoncorretto:17.0.5-alpine
COPY target/livraria-devops-0.0.1-SNAPSHOT.jar /tmp/livraria-devops-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/tmp/livraria-devops-0.0.1-SNAPSHOT.jar"]
